---
title: "Linear Models"
output: github_document
---

```{r}
library(tidyverse)

knitr::opts_chunk$set(
  fig.width = 6,
  fig.asp = .6,
  out.width = "90%"
)

theme_set(theme_minimal() + theme(legend.position = "bottom"))

options(
  ggplot2.continuous.colour = "viridis",
  ggplot2.continuous.fill = "viridis"
)

scale_colour_discrete = scale_colour_viridis_d
scale_fill_discrete = scale_fill_viridis_d
```


Load key packages

```{r}
library(tidyverse)
library(p8105.datasets)
```


Do some data cleaning.

```{r}
data("nyc_airbnb")

nyc_airbnb = 
  nyc_airbnb |> 
  mutate(stars = review_scores_location / 2) |> 
  rename(
    borough = neighbourhood_group,
    neighborhood = neighbourhood
  ) |> 
  filter(
    borough != "Staten Island"
  ) |> 
  select(price, stars, borough, neighborhood, room_type)
```

## Fit some models

Start relatively simple.

```{r}
fit = lm(price ~ stars, data = nyc_airbnb)

summary(fit)

names(summary(fit))

coef(fit)

fit |> 
  broom::tidy() |>  #used most commonly; includes summary table in a tidy format
  select(term, estimate, p.value)

fit |> 
  broom::glance() #also has summary, df, can be useful to eval model fit
```

Try a bit more complex

```{r}
fit =
  lm(price ~ stars + borough, data = nyc_airbnb) #R puts categorical variable in alphabetical order to determine factor order, so here "Bronx" becomes a REF category by default

fit |> 
  broom::tidy() |> 
  select(term, estimate, p.value) |> 
  mutate(
    term = str_replace(term, "borough", "Borough: ") #to make it look tidier
  ) |> 
  knitr::kable(digits = 3)
```





